### ISSUE TITLE
Base URL? (Step 2)

### ISSUE THREAD

**Issue by redpwilliams** [ZekeSnider/NintendoSwitchRESTAPI#15]
First time making posts...
Need example post request

**Comment by ZekeSnider** [comment]
On the [blueprint pages](https://github.com/ZekeSnider/NintendoSwitchRESTAPI/blob/master/NintendoAccountBlueprint.md) the host is listed on the first line of the file.

**Comment by redpwilliams** [comment]
I have it now, the only problem is that it it didn't list a session token. I have included the response I got. Any help would be greatly appreciated. Thanks!
[curl_response.txt](https://github.com/ZekeSnider/NintendoSwitchRESTAPI/files/4498214/curl_response.txt)
