### ISSUE TITLE
Salmon Run /api/records/hero

### ISSUE THREAD

**Issue by timtlm** [ZekeSnider/NintendoSwitchRESTAPI#3]
This is not salmon run info.  This is actually stats from the single player campaign mode.  I was hoping to be able to pull more details about the salmon run schedule and weapon sets, but all we get is whether there is a current salmon run going on using the /api/results.  I wonder if the switch uses the same api to pull this information for salmon run schedule.  Could it be possible to sniff the request using router network activity logging?

**Comment by Virepri** [comment]
Fixed this in my pull request.
