### ISSUE TITLE
reverse engineer the invite system

### ISSUE THREAD

**Issue by hymm** [ZekeSnider/NintendoSwitchRESTAPI#5]
Any plans to reverse engineer the invite system for splatoon private lobbies?  I've gotten a request to add it into SquidTracks, but am too busy adding other things to reverse engineer this.

**Comment by Virepri** [comment]
Sure thing. I don't know how well it'll go, but I'll give it a shot.

**Comment by Virepri** [comment]
![New functions](https://i.imgur.com/TONexKp.png)

Found a whole boatload of new things.
