### ISSUE TITLE
Changes to /v1/Account/Login in NSO v1.4.1

### ISSUE THREAD

**Issue by frozenpandaman** [ZekeSnider/NintendoSwitchRESTAPI#9]
Along with the v1.4.1 app update, it seems the login process now involves a few new parameters, a UUID version 4 and unix (epoch) timestamp:
```
"requestId": "123e4567-e89b-12d3-a456-426655440000",
"timestamp": 1537249847
```

Without these you get a "Bad request" error.

More info & thread at `https://github.com/frozenpandaman/splatnet2statink/issues/56#issuecomment-422314167`

**Comment by ZekeSnider** [comment]
Added detail on parameters in #10
